### ISSUE TITLE
Wishlist Issue with B2b Portal

### ISSUE THREAD

**Issue by SunilP-WassDigital** [bigcommerce/b2b-buyer-portal#54] opened 2024-06-27 12:14 UTC
**Type:** (Select one)
- [ ] Bug Report

**Summary:**

I m using B2b portal. In that wish list link there(home page, category page). When i click it is going to B2b login Page. After login it is continuous going to login page popup. 

**Expected Behavior:**

* After login it should be redirect to wish list page.

**Actual Behavior:**
* It is redirect to login to login page even i m  login

More information :
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.06.27-17_45_59.webm](https://github.com/bigcommerce/b2b-buyer-portal/assets/169963266/85e262ef-5774-4543-ae65-41c97504239e)

Let us know if you need more information

**Comment by bc-victor** [comment] 2024-07-01 16:48
Hi @SunilP-WassDigital, according to your test it redirected you to the login page. But by default it should redirect to register. Is there any customizations from your part on this workflow? thanks

![test](https://github.com/bigcommerce/b2b-buyer-portal/assets/140021227/988ca597-d7af-46bc-bba6-7399fcd4d7a8)

**Comment by SunilP-WassDigital** [comment] 2024-07-02 05:19
Hello @bc-victor 
As I see you are checking shopping list, i m asking for wishlist.

Please disable shopping list from company and check it.

**Comment by bc-victor** [comment] 2024-07-04 19:30
@SunilP-WassDigital could you show me the exact setting? I can't reproduce by disabling it here:
<img width="1624" alt="Screenshot 2024-07-04 at 1 30 05 p m" src="https://github.com/bigcommerce/b2b-buyer-portal/assets/140021227/4216350c-3132-4b72-a686-99164d02545d">

Video of test:
![test](https://github.com/bigcommerce/b2b-buyer-portal/assets/140021227/bfc5bcea-5b75-4ef4-b393-3618421e7ceb)

**Comment by SunilP-WassDigital** [comment] 2024-07-08 10:29
Hello @bc-victor 

No setting we added into our side, may be recently did some fix for that.

but still it is not right. after login should be redirect to wish list page directly, currently it is redirect to account page and still item not adding item into wish list.

**Comment by bc-victor** [comment] 2024-07-08 16:14
@SunilP-WassDigital 

> after login should be redirect to wish list page directly
AFAIK there is no Wish List page in the buyer portal. If so could you direct me to the hash route or provide a screenshot? 
If you mean it should redirect to the stencil wish list page - I'd have to ask the product team if that is actually expected behavior.

**Comment by bc-victor** [comment] 2024-07-17 15:19
According to our product team stencil wish lists page should never exists for Buyer Portal stores, once the user logged in, a better place to redirect would be the Buyer Portal Shopping Lists tab - will create a ticket for this behavior

**Comment by bc-victor** [comment] 2024-11-19 21:36
Closing as no further communication continued

**Closed by bc-victor** 2024-11-19 21:36 UTC
